### ISSUE TITLE
‘Automatically launch on Windows startup’ is not working

### ISSUE THREAD

**Issue by lalomartins** [TheJoeFin/Caffeinated#1]
Apparently, a ‘regular’ app packed and installed via store can't be executed by a traditional shortcut, so the ‘Automatically launch on Windows startup’ option is not working when the app is installed from the store.

**Comment by TheJoeFin** [comment]
Should be fixed in 1.1. Currently in certification.

**Comment by lalomartins** [comment]
I would like to confirm the fix, but the success was unfortunately partial.

After enabling the option in the app, it didn't launch in the next login. So I remembered something I read somewhere, and went to Task Manager, Startup tab, and it was there, but disabled. I enabled it, logged out, logged in again, and this time it launched correctly.

I don't know if there's a way to automate that. If not, then I guess add a message telling the user to do it?

**Comment by TheJoeFin** [comment]
I will make a new issue about this new behavior. I noticed the same thing when I was testing the update via the store on my laptop. Did you restart your PC after the update? The API is supposed to try to enable the on login behavior but there may be some async issue.

**Comment by lalomartins** [comment]
Yes, I restarted. After the restart the app didn't start, and it was disabled in the startup tab.
