### ISSUE TITLE
bring back more duration options

### ISSUE THREAD

**Issue by willnorris** [TheJoeFin/Caffeinated#10]
I know that reducing the number of duration options was one of the first changes you made in d5f91b58efbb5c0bd3e7908930fa6f0da68de41f, but would you consider bringing some of them back?  

Particularly in light of now working from home due to COVID, I find myself wanting to keep the machine awake for the duration of the workday, since my home office is a secure environment, and I feel comfortable leaving the screen unlocked all day.  So for that, the 5 hour option covered much of the day.  A more advanced option would be to make it user-configurable, but that would require quite a lot more work.

**Comment by TheJoeFin** [comment]
I'll bring back 5hrs for sure, and look into adding user configurable times as well.

**Comment by TheJoeFin** [comment]
Added 2hrs and 8hrs back. Making a new issue for user configurable times.
