### ISSUE TITLE
Black icon in Dark mode

### ISSUE THREAD

**Issue by redblackbst** [TheJoeFin/Caffeinated#19]
With the latest version (1.3.1.0 on Microsoft Store), the icon is black no matter what the taskbar theme mode is (Light or Dark).
![caffeinated-dark-taskbar](https://user-images.githubusercontent.com/14046170/104087962-4e7c2000-529e-11eb-8f39-37d6f3a4a53c.png)

**Comment by TheJoeFin** [comment]
Please open Caffeinated settings then click OK. This should reset the icon and it should pick the correct theme.

**Comment by r0gi** [comment]
I also have this issue. There is no OK button in the settings but I think closing saves them. 

Also, my icon always starts with the eye open even though I have the "Activate upon launch" unchecked in the settings, which makes the indicator icon reversed: 
<img width="137" alt="caffeinated sleep allowed" src="https://user-images.githubusercontent.com/47291559/104112133-e128c780-534f-11eb-90d5-50452792cc27.png">
<img width="150" alt="caffeinated sleep not allowed" src="https://user-images.githubusercontent.com/47291559/104112151-103f3900-5350-11eb-8283-9fe5c10302f2.png">

**Comment by TheJoeFin** [comment]
Does that happen for for every icon or just the default (eye & half eye) one?

**Comment by redblackbst** [comment]
> Please open Caffeinated settings then click OK. This should reset the icon and it should pick the correct theme.

No, it does not. And this is the case with all three sets of icons.

**Comment by TheJoeFin** [comment]
Can you share what your color theme preferences are for Windows:
![image](https://user-images.githubusercontent.com/7809853/104204358-d115f400-53f2-11eb-8066-6f38a6c0bcf7.png)

**Comment by redblackbst** [comment]
![color_theme_pref](https://user-images.githubusercontent.com/14046170/104262642-f83bf680-54c2-11eb-9afc-a7a1dccd612f.png)

**Comment by r0gi** [comment]
I have the same setup as redblackbst. I just noticed setting my 'default app mode' to dark gives the correct icon color (white). The solution is probably to check whatever maps to the "default windows mode" rather than "default app mode".

**Comment by r0gi** [comment]
I'm not well versed in windows app development or C#, but according to a quick google search you have to check the `SystemUsesLightTheme` key in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize`.

<img width="519" alt="theme_registry" src="https://user-images.githubusercontent.com/47291559/104281296-2b59a680-5512-11eb-8049-5ecf25561e60.png">

The taskbar is light when I set its value to 1.

**Comment by h0ek** [comment]
Same issue here :(

**Comment by TheJoeFin** [comment]
Version 1.3.2 submitted to Microsoft Store with this fixed.

**Comment by r0gi** [comment]
Looks good now. Thank you!
