### ISSUE TITLE
Adaptive icon does not change after theme switch

### ISSUE THREAD

**Issue by IgnusG** [TheJoeFin/Caffeinated#24]
Switching themes will not update the caffeinated icon until you right click it, go to settings and then close them. Until then it will stay the previous color scheme. 

This breaks a bit if the theme is changed automatically at night for example. I assume it might be possible to either detect the change or periodically check it but not sure if the latter wouldn't waste resources on something that happens fairly rarely.

<details>
<summary>System Information</summary>
<ul>
<li>Windows: 10.0.19043 Build 19043 (Insider Stable)</li>
<li>Caffeinated: 1.5.0.0</li>
</ul>
</details>

> Thanks for this app! It's really super useful

**Comment by IgnusG** [comment]
https://user-images.githubusercontent.com/6438760/123699916-170b2b00-d860-11eb-85e9-02cd51032867.mp4

**Comment by TheJoeFin** [comment]
This has been fixed, update will roll out to the Store soon.
