### ISSUE TITLE
Default duration setting not applied when application auto-starts with Windows

### ISSUE THREAD

**Issue by gokieks** [TheJoeFin/Caffeinated#29]
Was setting up a new PC and saw this was a forked and newer version of what I had previously been using (Caffeinated from Desmond Brand), so decided to try it - using version 1.7.0 from Microsoft Store.  However, I've found that regardless of what the default duration I select in settings is, when the app automatically launches after Windows login, it will always default to 8 hours.

As I absolutely need my prevent-sleep app to auto start and also stay active indefinitely, that makes this version unusable for me.

**Comment by TheJoeFin** [comment]
I'll take a look at this and see what could be going on

**Comment by TheJoeFin** [comment]
I found the issue! New version 1.8.0 has been submitted to the Windows Store.
